[workspace]
channels = ["https://prefix.dev/conda-forge"]
platforms = ["osx-arm64", "linux-64"]
preview = ["pixi-build"]

[package]
version = "9999.0.0"

[package.build.backend]
name = "pixi-build-python"
version = "*"

[package.build.source]
git = "https://github.com/gmpy2/gmpy2"

[package.build.config]
ignore-pypi-mapping = false
compilers = ["c"]

[package.host-dependencies]
uv = "*"
gmp = "*"
mpfr = "*"
mpc = "*"
