name: Forge
on:
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  forge:
    name: ${{ matrix.name }} ${{ matrix.os }}
    permissions:
      id-token: write  # Required for OIDC token
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          # - name: scipy
          #   type: remote
          #   repo: scipy/scipy
          #   subdir: ''
          # - name: numpy
          #   type: remote
          #   repo: numpy/numpy
          #   subdir: pixi-packages/default
          - name: array-api-extra
            type: remote
            repo: data-apis/array-api-extra
            subdir: ''
            os: ubuntu-latest
          - name: xarray
            type: remote
            repo: pydata/xarray
            subdir: ''
            os: ubuntu-latest
          - name: scikit-learn
            type: local
            repo: ''
            subdir: ''
    steps:
      - name: checkout remote
        if: ${{ matrix.type == 'remote' }}
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          repository: ${{ matrix.repo }}
          path: packages/${{ matrix.name }}
          submodules: recursive
          persist-credentials: false
      - name: checkout local
        if: ${{ matrix.type == 'local' }}
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - name: setup-pixi
        uses: prefix-dev/setup-pixi@a0af7a228712d6121d37aba47adf55c1332c9c2e # v0.9.4
        with:
          run-install: false
      - name: publish
        # TODO: --generate-attestation
        run: pixi publish --path ${PKG_PATH} --to https://prefix.dev/sp-nightly-forge
        env:
          PKG_PATH: packages/${{ matrix.subdir && format('{0}/{1}', matrix.name, matrix.subdir) || matrix.name }}
