name: Forge
on:
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  forge:
    name: ${{ matrix.package.name }} ${{ matrix.os }}
    permissions:
      id-token: write  # Required for OIDC token
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        package:
          - name: scipy
            type: remote
            repo: scipy/scipy
            subdir: ''
            noarch: false
          - name: numpy
            type: remote
            repo: numpy/numpy
            subdir: pixi-packages/default
            noarch: false
          - name: scikit-learn
            type: local
            repo: ''
            subdir: ''
            noarch: false
          - name: array-api-extra
            type: remote
            repo: data-apis/array-api-extra
            subdir: ''
            noarch: true
          - name: xarray
            type: remote
            repo: pydata/xarray
            subdir: ''
            noarch: true
        exclude:
          - package:
              noarch: true
            os: windows-latest
          - package:
              noarch: true
            os: macos-latest
          - package:
              name: scikit-learn
            os: windows-latest
            
            
    steps:
      - name: checkout remote
        if: ${{ matrix.package.type == 'remote' }}
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          repository: ${{ matrix.package.repo }}
          path: packages/${{ matrix.package.name }}
          submodules: recursive
          persist-credentials: false
      - name: checkout local
        if: ${{ matrix.package.type == 'local' }}
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - name: setup-pixi
        uses: prefix-dev/setup-pixi@a0af7a228712d6121d37aba47adf55c1332c9c2e # v0.9.4
        with:
          run-install: false
      - name: publish
        # TODO: --generate-attestation
        run: pixi publish --path ${PKG_PATH} --to https://prefix.dev/sp-nightly-forge
        env:
          PKG_PATH: ${{ matrix.os == 'windows-latest'
              && (matrix.package.subdir && format('packages\\{0}\\{1}', matrix.package.name, matrix.package.subdir) || format('packages\\{0}', matrix.package.name))
              || (matrix.package.subdir && format('packages/{0}/{1}', matrix.package.name, matrix.package.subdir) || format('packages/{0}', matrix.package.name))
            }}
